// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"pinares/ent/migrate"

	"pinares/ent/apartment"
	"pinares/ent/tower"
	"pinares/ent/user"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// Apartment is the client for interacting with the Apartment builders.
	Apartment *ApartmentClient
	// Tower is the client for interacting with the Tower builders.
	Tower *TowerClient
	// User is the client for interacting with the User builders.
	User *UserClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.Apartment = NewApartmentClient(c.config)
	c.Tower = NewTowerClient(c.config)
	c.User = NewUserClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Apartment: NewApartmentClient(cfg),
		Tower:     NewTowerClient(cfg),
		User:      NewUserClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		Apartment: NewApartmentClient(cfg),
		Tower:     NewTowerClient(cfg),
		User:      NewUserClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		Apartment.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.Apartment.Use(hooks...)
	c.Tower.Use(hooks...)
	c.User.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.Apartment.Intercept(interceptors...)
	c.Tower.Intercept(interceptors...)
	c.User.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *ApartmentMutation:
		return c.Apartment.mutate(ctx, m)
	case *TowerMutation:
		return c.Tower.mutate(ctx, m)
	case *UserMutation:
		return c.User.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// ApartmentClient is a client for the Apartment schema.
type ApartmentClient struct {
	config
}

// NewApartmentClient returns a client for the Apartment from the given config.
func NewApartmentClient(c config) *ApartmentClient {
	return &ApartmentClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `apartment.Hooks(f(g(h())))`.
func (c *ApartmentClient) Use(hooks ...Hook) {
	c.hooks.Apartment = append(c.hooks.Apartment, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `apartment.Intercept(f(g(h())))`.
func (c *ApartmentClient) Intercept(interceptors ...Interceptor) {
	c.inters.Apartment = append(c.inters.Apartment, interceptors...)
}

// Create returns a builder for creating a Apartment entity.
func (c *ApartmentClient) Create() *ApartmentCreate {
	mutation := newApartmentMutation(c.config, OpCreate)
	return &ApartmentCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Apartment entities.
func (c *ApartmentClient) CreateBulk(builders ...*ApartmentCreate) *ApartmentCreateBulk {
	return &ApartmentCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *ApartmentClient) MapCreateBulk(slice any, setFunc func(*ApartmentCreate, int)) *ApartmentCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &ApartmentCreateBulk{err: fmt.Errorf("calling to ApartmentClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*ApartmentCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &ApartmentCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Apartment.
func (c *ApartmentClient) Update() *ApartmentUpdate {
	mutation := newApartmentMutation(c.config, OpUpdate)
	return &ApartmentUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *ApartmentClient) UpdateOne(a *Apartment) *ApartmentUpdateOne {
	mutation := newApartmentMutation(c.config, OpUpdateOne, withApartment(a))
	return &ApartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *ApartmentClient) UpdateOneID(id int) *ApartmentUpdateOne {
	mutation := newApartmentMutation(c.config, OpUpdateOne, withApartmentID(id))
	return &ApartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Apartment.
func (c *ApartmentClient) Delete() *ApartmentDelete {
	mutation := newApartmentMutation(c.config, OpDelete)
	return &ApartmentDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *ApartmentClient) DeleteOne(a *Apartment) *ApartmentDeleteOne {
	return c.DeleteOneID(a.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *ApartmentClient) DeleteOneID(id int) *ApartmentDeleteOne {
	builder := c.Delete().Where(apartment.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &ApartmentDeleteOne{builder}
}

// Query returns a query builder for Apartment.
func (c *ApartmentClient) Query() *ApartmentQuery {
	return &ApartmentQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeApartment},
		inters: c.Interceptors(),
	}
}

// Get returns a Apartment entity by its id.
func (c *ApartmentClient) Get(ctx context.Context, id int) (*Apartment, error) {
	return c.Query().Where(apartment.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *ApartmentClient) GetX(ctx context.Context, id int) *Apartment {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryOwner queries the owner edge of a Apartment.
func (c *ApartmentClient) QueryOwner(a *Apartment) *UserQuery {
	query := (&UserClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := a.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(apartment.Table, apartment.FieldID, id),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, apartment.OwnerTable, apartment.OwnerColumn),
		)
		fromV = sqlgraph.Neighbors(a.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *ApartmentClient) Hooks() []Hook {
	return c.hooks.Apartment
}

// Interceptors returns the client interceptors.
func (c *ApartmentClient) Interceptors() []Interceptor {
	return c.inters.Apartment
}

func (c *ApartmentClient) mutate(ctx context.Context, m *ApartmentMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&ApartmentCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&ApartmentUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&ApartmentUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&ApartmentDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Apartment mutation op: %q", m.Op())
	}
}

// TowerClient is a client for the Tower schema.
type TowerClient struct {
	config
}

// NewTowerClient returns a client for the Tower from the given config.
func NewTowerClient(c config) *TowerClient {
	return &TowerClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tower.Hooks(f(g(h())))`.
func (c *TowerClient) Use(hooks ...Hook) {
	c.hooks.Tower = append(c.hooks.Tower, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `tower.Intercept(f(g(h())))`.
func (c *TowerClient) Intercept(interceptors ...Interceptor) {
	c.inters.Tower = append(c.inters.Tower, interceptors...)
}

// Create returns a builder for creating a Tower entity.
func (c *TowerClient) Create() *TowerCreate {
	mutation := newTowerMutation(c.config, OpCreate)
	return &TowerCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tower entities.
func (c *TowerClient) CreateBulk(builders ...*TowerCreate) *TowerCreateBulk {
	return &TowerCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *TowerClient) MapCreateBulk(slice any, setFunc func(*TowerCreate, int)) *TowerCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &TowerCreateBulk{err: fmt.Errorf("calling to TowerClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*TowerCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &TowerCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tower.
func (c *TowerClient) Update() *TowerUpdate {
	mutation := newTowerMutation(c.config, OpUpdate)
	return &TowerUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TowerClient) UpdateOne(t *Tower) *TowerUpdateOne {
	mutation := newTowerMutation(c.config, OpUpdateOne, withTower(t))
	return &TowerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TowerClient) UpdateOneID(id int) *TowerUpdateOne {
	mutation := newTowerMutation(c.config, OpUpdateOne, withTowerID(id))
	return &TowerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tower.
func (c *TowerClient) Delete() *TowerDelete {
	mutation := newTowerMutation(c.config, OpDelete)
	return &TowerDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *TowerClient) DeleteOne(t *Tower) *TowerDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *TowerClient) DeleteOneID(id int) *TowerDeleteOne {
	builder := c.Delete().Where(tower.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TowerDeleteOne{builder}
}

// Query returns a query builder for Tower.
func (c *TowerClient) Query() *TowerQuery {
	return &TowerQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeTower},
		inters: c.Interceptors(),
	}
}

// Get returns a Tower entity by its id.
func (c *TowerClient) Get(ctx context.Context, id int) (*Tower, error) {
	return c.Query().Where(tower.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TowerClient) GetX(ctx context.Context, id int) *Tower {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// QueryApartments queries the apartments edge of a Tower.
func (c *TowerClient) QueryApartments(t *Tower) *ApartmentQuery {
	query := (&ApartmentClient{config: c.config}).Query()
	query.path = func(context.Context) (fromV *sql.Selector, _ error) {
		id := t.ID
		step := sqlgraph.NewStep(
			sqlgraph.From(tower.Table, tower.FieldID, id),
			sqlgraph.To(apartment.Table, apartment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tower.ApartmentsTable, tower.ApartmentsColumn),
		)
		fromV = sqlgraph.Neighbors(t.driver.Dialect(), step)
		return fromV, nil
	}
	return query
}

// Hooks returns the client hooks.
func (c *TowerClient) Hooks() []Hook {
	return c.hooks.Tower
}

// Interceptors returns the client interceptors.
func (c *TowerClient) Interceptors() []Interceptor {
	return c.inters.Tower
}

func (c *TowerClient) mutate(ctx context.Context, m *TowerMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&TowerCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&TowerUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&TowerUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&TowerDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown Tower mutation op: %q", m.Op())
	}
}

// UserClient is a client for the User schema.
type UserClient struct {
	config
}

// NewUserClient returns a client for the User from the given config.
func NewUserClient(c config) *UserClient {
	return &UserClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `user.Hooks(f(g(h())))`.
func (c *UserClient) Use(hooks ...Hook) {
	c.hooks.User = append(c.hooks.User, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `user.Intercept(f(g(h())))`.
func (c *UserClient) Intercept(interceptors ...Interceptor) {
	c.inters.User = append(c.inters.User, interceptors...)
}

// Create returns a builder for creating a User entity.
func (c *UserClient) Create() *UserCreate {
	mutation := newUserMutation(c.config, OpCreate)
	return &UserCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of User entities.
func (c *UserClient) CreateBulk(builders ...*UserCreate) *UserCreateBulk {
	return &UserCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *UserClient) MapCreateBulk(slice any, setFunc func(*UserCreate, int)) *UserCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &UserCreateBulk{err: fmt.Errorf("calling to UserClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*UserCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &UserCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for User.
func (c *UserClient) Update() *UserUpdate {
	mutation := newUserMutation(c.config, OpUpdate)
	return &UserUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *UserClient) UpdateOne(u *User) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUser(u))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *UserClient) UpdateOneID(id int) *UserUpdateOne {
	mutation := newUserMutation(c.config, OpUpdateOne, withUserID(id))
	return &UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for User.
func (c *UserClient) Delete() *UserDelete {
	mutation := newUserMutation(c.config, OpDelete)
	return &UserDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *UserClient) DeleteOne(u *User) *UserDeleteOne {
	return c.DeleteOneID(u.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *UserClient) DeleteOneID(id int) *UserDeleteOne {
	builder := c.Delete().Where(user.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &UserDeleteOne{builder}
}

// Query returns a query builder for User.
func (c *UserClient) Query() *UserQuery {
	return &UserQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeUser},
		inters: c.Interceptors(),
	}
}

// Get returns a User entity by its id.
func (c *UserClient) Get(ctx context.Context, id int) (*User, error) {
	return c.Query().Where(user.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *UserClient) GetX(ctx context.Context, id int) *User {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *UserClient) Hooks() []Hook {
	return c.hooks.User
}

// Interceptors returns the client interceptors.
func (c *UserClient) Interceptors() []Interceptor {
	return c.inters.User
}

func (c *UserClient) mutate(ctx context.Context, m *UserMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&UserCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&UserUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&UserUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&UserDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown User mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		Apartment, Tower, User []ent.Hook
	}
	inters struct {
		Apartment, Tower, User []ent.Interceptor
	}
)
