// Code generated by ent, DO NOT EDIT.

package ent

import (
	"pinares/ent/schema"
	"pinares/ent/tower"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	towerFields := schema.Tower{}.Fields()
	_ = towerFields
	// towerDescNumberOfFloors is the schema descriptor for number_of_floors field.
	towerDescNumberOfFloors := towerFields[0].Descriptor()
	// tower.NumberOfFloorsValidator is a validator for the "number_of_floors" field. It is called by the builders before save.
	tower.NumberOfFloorsValidator = towerDescNumberOfFloors.Validators[0].(func(int) error)
	// towerDescNumberOfApartmentsPerFloor is the schema descriptor for number_of_apartments_per_floor field.
	towerDescNumberOfApartmentsPerFloor := towerFields[1].Descriptor()
	// tower.NumberOfApartmentsPerFloorValidator is a validator for the "number_of_apartments_per_floor" field. It is called by the builders before save.
	tower.NumberOfApartmentsPerFloorValidator = towerDescNumberOfApartmentsPerFloor.Validators[0].(func(int) error)
	// towerDescName is the schema descriptor for name field.
	towerDescName := towerFields[2].Descriptor()
	// tower.DefaultName holds the default value on creation for the name field.
	tower.DefaultName = towerDescName.Default.(string)
}
