// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"
	"pinares/ent/apartment"
	"pinares/ent/predicate"
	"pinares/ent/tower"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TowerQuery is the builder for querying Tower entities.
type TowerQuery struct {
	config
	ctx            *QueryContext
	order          []tower.OrderOption
	inters         []Interceptor
	predicates     []predicate.Tower
	withApartments *ApartmentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TowerQuery builder.
func (tq *TowerQuery) Where(ps ...predicate.Tower) *TowerQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit the number of records to be returned by this query.
func (tq *TowerQuery) Limit(limit int) *TowerQuery {
	tq.ctx.Limit = &limit
	return tq
}

// Offset to start from.
func (tq *TowerQuery) Offset(offset int) *TowerQuery {
	tq.ctx.Offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TowerQuery) Unique(unique bool) *TowerQuery {
	tq.ctx.Unique = &unique
	return tq
}

// Order specifies how the records should be ordered.
func (tq *TowerQuery) Order(o ...tower.OrderOption) *TowerQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryApartments chains the current query on the "apartments" edge.
func (tq *TowerQuery) QueryApartments() *ApartmentQuery {
	query := (&ApartmentClient{config: tq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(tower.Table, tower.FieldID, selector),
			sqlgraph.To(apartment.Table, apartment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, tower.ApartmentsTable, tower.ApartmentsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Tower entity from the query.
// Returns a *NotFoundError when no Tower was found.
func (tq *TowerQuery) First(ctx context.Context) (*Tower, error) {
	nodes, err := tq.Limit(1).All(setContextOp(ctx, tq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{tower.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TowerQuery) FirstX(ctx context.Context) *Tower {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Tower ID from the query.
// Returns a *NotFoundError when no Tower ID was found.
func (tq *TowerQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(setContextOp(ctx, tq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{tower.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TowerQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Tower entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Tower entity is found.
// Returns a *NotFoundError when no Tower entities are found.
func (tq *TowerQuery) Only(ctx context.Context) (*Tower, error) {
	nodes, err := tq.Limit(2).All(setContextOp(ctx, tq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{tower.Label}
	default:
		return nil, &NotSingularError{tower.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TowerQuery) OnlyX(ctx context.Context) *Tower {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Tower ID in the query.
// Returns a *NotSingularError when more than one Tower ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TowerQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(setContextOp(ctx, tq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{tower.Label}
	default:
		err = &NotSingularError{tower.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TowerQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Towers.
func (tq *TowerQuery) All(ctx context.Context) ([]*Tower, error) {
	ctx = setContextOp(ctx, tq.ctx, "All")
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Tower, *TowerQuery]()
	return withInterceptors[[]*Tower](ctx, tq, qr, tq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tq *TowerQuery) AllX(ctx context.Context) []*Tower {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Tower IDs.
func (tq *TowerQuery) IDs(ctx context.Context) (ids []int, err error) {
	if tq.ctx.Unique == nil && tq.path != nil {
		tq.Unique(true)
	}
	ctx = setContextOp(ctx, tq.ctx, "IDs")
	if err = tq.Select(tower.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TowerQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TowerQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tq.ctx, "Count")
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tq, querierCount[*TowerQuery](), tq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TowerQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TowerQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tq.ctx, "Exist")
	switch _, err := tq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TowerQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TowerQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TowerQuery) Clone() *TowerQuery {
	if tq == nil {
		return nil
	}
	return &TowerQuery{
		config:         tq.config,
		ctx:            tq.ctx.Clone(),
		order:          append([]tower.OrderOption{}, tq.order...),
		inters:         append([]Interceptor{}, tq.inters...),
		predicates:     append([]predicate.Tower{}, tq.predicates...),
		withApartments: tq.withApartments.Clone(),
		// clone intermediate query.
		sql:  tq.sql.Clone(),
		path: tq.path,
	}
}

// WithApartments tells the query-builder to eager-load the nodes that are connected to
// the "apartments" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TowerQuery) WithApartments(opts ...func(*ApartmentQuery)) *TowerQuery {
	query := (&ApartmentClient{config: tq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tq.withApartments = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		NumberOfFloors int `json:"number_of_floors,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Tower.Query().
//		GroupBy(tower.FieldNumberOfFloors).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tq *TowerQuery) GroupBy(field string, fields ...string) *TowerGroupBy {
	tq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TowerGroupBy{build: tq}
	grbuild.flds = &tq.ctx.Fields
	grbuild.label = tower.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		NumberOfFloors int `json:"number_of_floors,omitempty"`
//	}
//
//	client.Tower.Query().
//		Select(tower.FieldNumberOfFloors).
//		Scan(ctx, &v)
func (tq *TowerQuery) Select(fields ...string) *TowerSelect {
	tq.ctx.Fields = append(tq.ctx.Fields, fields...)
	sbuild := &TowerSelect{TowerQuery: tq}
	sbuild.label = tower.Label
	sbuild.flds, sbuild.scan = &tq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TowerSelect configured with the given aggregations.
func (tq *TowerQuery) Aggregate(fns ...AggregateFunc) *TowerSelect {
	return tq.Select().Aggregate(fns...)
}

func (tq *TowerQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tq); err != nil {
				return err
			}
		}
	}
	for _, f := range tq.ctx.Fields {
		if !tower.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TowerQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Tower, error) {
	var (
		nodes       = []*Tower{}
		_spec       = tq.querySpec()
		loadedTypes = [1]bool{
			tq.withApartments != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Tower).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Tower{config: tq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tq.withApartments; query != nil {
		if err := tq.loadApartments(ctx, query, nodes,
			func(n *Tower) { n.Edges.Apartments = []*Apartment{} },
			func(n *Tower, e *Apartment) { n.Edges.Apartments = append(n.Edges.Apartments, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tq *TowerQuery) loadApartments(ctx context.Context, query *ApartmentQuery, nodes []*Tower, init func(*Tower), assign func(*Tower, *Apartment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*Tower)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Apartment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(tower.ApartmentsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.tower_apartments
		if fk == nil {
			return fmt.Errorf(`foreign-key "tower_apartments" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "tower_apartments" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (tq *TowerQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.ctx.Fields
	if len(tq.ctx.Fields) > 0 {
		_spec.Unique = tq.ctx.Unique != nil && *tq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TowerQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(tower.Table, tower.Columns, sqlgraph.NewFieldSpec(tower.FieldID, field.TypeInt))
	_spec.From = tq.sql
	if unique := tq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tq.path != nil {
		_spec.Unique = true
	}
	if fields := tq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tower.FieldID)
		for i := range fields {
			if fields[i] != tower.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TowerQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(tower.Table)
	columns := tq.ctx.Fields
	if len(columns) == 0 {
		columns = tower.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.ctx.Unique != nil && *tq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TowerGroupBy is the group-by builder for Tower entities.
type TowerGroupBy struct {
	selector
	build *TowerQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TowerGroupBy) Aggregate(fns ...AggregateFunc) *TowerGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the selector query and scans the result into the given value.
func (tgb *TowerGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tgb.build.ctx, "GroupBy")
	if err := tgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TowerQuery, *TowerGroupBy](ctx, tgb.build, tgb, tgb.build.inters, v)
}

func (tgb *TowerGroupBy) sqlScan(ctx context.Context, root *TowerQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tgb.flds)+len(tgb.fns))
		for _, f := range *tgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TowerSelect is the builder for selecting fields of Tower entities.
type TowerSelect struct {
	*TowerQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ts *TowerSelect) Aggregate(fns ...AggregateFunc) *TowerSelect {
	ts.fns = append(ts.fns, fns...)
	return ts
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TowerSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ts.ctx, "Select")
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TowerQuery, *TowerSelect](ctx, ts.TowerQuery, ts, ts.inters, v)
}

func (ts *TowerSelect) sqlScan(ctx context.Context, root *TowerQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ts.fns))
	for _, fn := range ts.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ts.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
