// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Apartment is the predicate function for apartment builders.
type Apartment func(*sql.Selector)

// Tower is the predicate function for tower builders.
type Tower func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
